---
title: "Parallel process models"
format: html
editor: visual
---

```{r}
# Read in data

library(here)
library(lavaan)
library(tidyverse)
library(broom)
library(semPlot)
data.wide <- read_csv(here('Generated Datasets', 'data_wide.rds'))
```

# PHQ9 and BPI interference parallel process

```{r}

phq9.BPI_Inter.parallel.model <- '

phqIntercept =~ 1*PHQ9.1 +
              1*PHQ9.2 +
              1*PHQ9.3 +
              1*PHQ9.4 +
              1*PHQ9.5
              
phqSlope1 =~ 0*PHQ9.1 +
              1*PHQ9.2 +
              2*PHQ9.3 +
              2*PHQ9.4 +
              2*PHQ9.5
              
phqSlope2 =~ 0*PHQ9.1 +
              0*PHQ9.2 +
              0*PHQ9.3 +
              1*PHQ9.4 +
              2*PHQ9.5
              

bpiInterIntercept =~ 1*BPIinterference.1 +
              1*BPIinterference.2 +
              1*BPIinterference.3 +
              1*BPIinterference.4 +
              1*BPIinterference.5
              
bpiInterSlope1 =~ 0*BPIinterference.1 +
              1*BPIinterference.2 +
              2*BPIinterference.3 +
              2*BPIinterference.4 +
              2*BPIinterference.5
              
bpiInterSlope2 =~ 0*BPIinterference.1 +
              0*BPIinterference.2 +
              0*BPIinterference.3 +
              1*BPIinterference.4 +
              2*BPIinterference.5              

# regress factors on age (moderator)
phqIntercept ~ ageMeanCentered
phqSlope1 ~ ageMeanCentered
phqSlope2 ~ ageMeanCentered

bpiInterIntercept ~ ageMeanCentered
bpiInterSlope1 ~ ageMeanCentered
bpiInterSlope2 ~ ageMeanCentered

# slope covariances
bpiInterSlope1 ~~ phqSlope1
bpiInterSlope2 ~~ phqSlope2
bpiInterSlope1 ~~ 0*phqSlope2
bpiInterSlope2 ~~ 0*phqSlope1

## fix negative RV to zero
PHQ9.3  ~~ 0*PHQ9.3  

'

phq9.BPI_Inter.parallel.fit <- lavaan::sem(model = phq9.BPI_Inter.parallel.model,
                        data = data.wide,
                        missing = 'FIML')

summary(phq9.BPI_Inter.parallel.fit, fit.measures = TRUE)


semPlot::semPaths(phq9.BPI_Inter.parallel.fit, 
                  layout = "tree2")
```

# PHQ9 and BPI severity parallel process

```{r}

phq9.BPI_Sev.parallel.model <- '

phqIntercept =~ 1*PHQ9.1 +
              1*PHQ9.2 +
              1*PHQ9.3 +
              1*PHQ9.4 +
              1*PHQ9.5
              
phqSlope1 =~ 0*PHQ9.1 +
              1*PHQ9.2 +
              2*PHQ9.3 +
              2*PHQ9.4 +
              2*PHQ9.5
              
phqSlope2 =~ 0*PHQ9.1 +
              0*PHQ9.2 +
              0*PHQ9.3 +
              1*PHQ9.4 +
              2*PHQ9.5
              

bpiSevIntercept =~ 1*BPIseverity.1 +
              1*BPIseverity.2 +
              1*BPIseverity.3 +
              1*BPIseverity.4 +
              1*BPIseverity.5
              
bpiSevSlope1 =~ 0*BPIseverity.1 +
              1*BPIseverity.2 +
              2*BPIseverity.3 +
              2*BPIseverity.4 +
              2*BPIseverity.5
              
bpiSevSlope2 =~ 0*BPIseverity.1 +
              0*BPIseverity.2 +
              0*BPIseverity.3 +
              1*BPIseverity.4 +
              2*BPIseverity.5              

# regress factors on age (moderator)
phqIntercept ~ ageMeanCentered
phqSlope1 ~ ageMeanCentered
phqSlope2 ~ ageMeanCentered

bpiSevIntercept ~ ageMeanCentered
bpiSevSlope1 ~ ageMeanCentered
bpiSevSlope2 ~ ageMeanCentered

# slope covariances
bpiSevSlope1 ~~ phqSlope1
bpiSevSlope2 ~~ phqSlope2
bpiSevSlope1 ~~ 0*phqSlope2
bpiSevSlope2 ~~ 0*phqSlope1

'

phq9.BPI_Sev.parallel.fit <- lavaan::sem(model = phq9.BPI_Sev.parallel.model,
                        data = data.wide,
                        missing = 'FIML')

summary(phq9.BPI_Sev.parallel.fit, fit.measures = TRUE)

```



# BPI severity and BPI interference parallel process

This model covariance matrix was NPD modeling both 3 and 5 timepoints. Unclear why...

```{r}

BPI_Sev.BPI_Inter.parallel.model <- '

bpiSevIntercept =~ 1*BPIseverity.1 +
              1*BPIseverity.2 +
              1*BPIseverity.3
              
bpiSevSlope1 =~ 0*BPIseverity.1 +
              1*BPIseverity.2 +
              2*BPIseverity.3

bpiInterIntercept =~ 1*BPIinterference.1 +
              1*BPIinterference.2 +
              1*BPIinterference.3
              
bpiInterSlope1 =~ 0*BPIinterference.1 +
              1*BPIinterference.2 +
              2*BPIinterference.3            

# regress factors on age (moderator)
bpiSevIntercept ~ ageMeanCentered
bpiSevSlope1 ~ ageMeanCentered

bpiInterIntercept ~ ageMeanCentered
bpiInterSlope1 ~ ageMeanCentered



'

BPI_Sev.BPI_Inter.parallel.fit <- lavaan::sem(model = BPI_Sev.BPI_Inter.parallel.model,
                        data = data.wide,
                        missing = 'FIML')

summary(BPI_Sev.BPI_Inter.parallel.fit, fit.measures = TRUE)

lavInspect(BPI_Sev.BPI_Inter.parallel.fit, "cov.lv")

```
