---
title: "Play with moderated models"
author: "Joel Fishbein"
date: '2022-10-11'
output: html_document
---

Age as moderator
Sleep dysfunction as moderator 

```{r}

data.wide <- data.wide %>%
  mutate(interaction = ageMeanCentered*Telehealth)


data.wide %>%
  ggplot(aes(x = ageMeanCentered, y = PSQI.1)) +
  geom_bar()

```

```{r}

model1 <- '

myIntercept =~ 1*BPIseverity.1 +
              1*BPIseverity.2 +
              1*BPIseverity.3 +
              1*BPIseverity.4 +
              1*BPIseverity.5
              
slope1 =~ 0*BPIseverity.1 +
              1*BPIseverity.2 +
              2*BPIseverity.3 +
              2*BPIseverity.4 +
              2*BPIseverity.5
              
slope2 =~ 0*BPIseverity.1 +
              0*BPIseverity.2 +
              0*BPIseverity.3 +
              1*BPIseverity.4 +
              2*BPIseverity.5

slope1 ~~ slope1Sigma2*slope1
slope2 ~~ slope2Sigma2*slope2
              
myIntercept ~ mIntercept*ageMeanCentered
slope1 ~ mSlope1*ageMeanCentered
slope2 ~ mSlope2*ageMeanCentered

#ageES_slope1 := mSlope1/sqrt(slope1Sigma2)
#ageES_slope2 := mSlope2/sqrt(slope2Sigma2)

              
'

fit1 <- lavaan::sem(model = model1, data = data.wide)

summary(fit1)

```


```{r}

model2 <- '

myIntercept =~ 1*BPIseverity.1 +
              1*BPIseverity.2 +
              1*BPIseverity.3 +
              1*BPIseverity.4 +
              1*BPIseverity.5
              
slope1 =~ 0*BPIseverity.1 +
              1*BPIseverity.2 +
              2*BPIseverity.3 +
              2*BPIseverity.4 +
              2*BPIseverity.5
              
slope2 =~ 0*BPIseverity.1 +
              0*BPIseverity.2 +
              0*BPIseverity.3 +
              1*BPIseverity.4 +
              2*BPIseverity.5

slope1 ~~ slope1Sigma2*slope1
slope2 ~~ slope2Sigma2*slope2
              
myIntercept ~ mIntercept*ageMeanCentered
slope1 ~ mSlope1*ageMeanCentered
slope2 ~ mSlope2*ageMeanCentered

myIntercept ~ Telehealth
slope1 ~ Telehealth
slope2 ~ Telehealth

#ageES_slope1 := mSlope1/sqrt(slope1Sigma2)
#ageES_slope2 := mSlope2/sqrt(slope2Sigma2)

              
'

fit2 <- lavaan::sem(model = model2, data = data.wide)

summary(fit2)

```

```{r}

model3 <- '

myIntercept =~ 1*BPIseverity.1 +
              1*BPIseverity.2 +
              1*BPIseverity.3 +
              1*BPIseverity.4 +
              1*BPIseverity.5
              
slope1 =~ 0*BPIseverity.1 +
              1*BPIseverity.2 +
              2*BPIseverity.3 +
              2*BPIseverity.4 +
              2*BPIseverity.5
              
slope2 =~ 0*BPIseverity.1 +
              0*BPIseverity.2 +
              0*BPIseverity.3 +
              1*BPIseverity.4 +
              2*BPIseverity.5

slope1 ~~ slope1Sigma2*slope1
slope2 ~~ slope2Sigma2*slope2
              
myIntercept ~ mIntercept*ageMeanCentered
slope1 ~ mSlope1*ageMeanCentered
slope2 ~ mSlope2*ageMeanCentered

myIntercept ~ Telehealth
slope1 ~ Telehealth
slope2 ~ Telehealth

myIntercept ~ interaction
slope1 ~ interaction
slope2 ~ interaction

#ageES_slope1 := mSlope1/sqrt(slope1Sigma2)
#ageES_slope2 := mSlope2/sqrt(slope2Sigma2)


              
'

fit3 <- lavaan::sem(model = model3, data = data.wide)

summary(fit3)

```


```{r}

model4 <- '

myIntercept =~ 1*BPIinterference.1 +
              1*BPIinterference.2 +
              1*BPIinterference.3 +
              1*BPIinterference.4 +
              1*BPIinterference.5
              
slope1 =~ 0*BPIinterference.1 +
              1*BPIinterference.2 +
              2*BPIinterference.3 +
              2*BPIinterference.4 +
              2*BPIinterference.5
              
slope2 =~ 0*BPIinterference.1 +
              0*BPIinterference.2 +
              0*BPIinterference.3 +
              1*BPIinterference.4 +
              2*BPIinterference.5

slope1 ~~ slope1Sigma2*slope1
slope2 ~~ slope2Sigma2*slope2
              
myIntercept ~ mIntercept*ageMeanCentered
slope1 ~ mSlope1*ageMeanCentered
slope2 ~ mSlope2*ageMeanCentered

myIntercept ~ Telehealth
slope1 ~ Telehealth
slope2 ~ Telehealth

myIntercept ~ interaction
slope1 ~ interaction
slope2 ~ interaction

#ageES_slope1 := mSlope1/sqrt(slope1Sigma2)
#ageES_slope2 := mSlope2/sqrt(slope2Sigma2)


              
'

fit4 <- lavaan::sem(model = model4, data = data.wide)

summary(fit4)

```