---
title: "Age Plot"
format: html
editor: visual
author: Joel N Fishbein, M.A.
date: March 24, 2022
---

```{r}

library(ggdist)
library(tidyverse)

data.wide <- read_csv(here('Generated Datasets', 'data_wide.rds'))


```

```{r}

data.wide %>% 
  select(age) %>%
  mutate(`25-34` = (age < 35),
         `35-44` = (age >= 35) & (age < 45),
         `45-54` = (age >= 45) & (age < 55),
         `55-64` = (age >= 55) & (age < 65),
         `65-74` = (age >= 65) & (age < 75),
         `75+` = (age >= 75)) %>%
  
  summarize(across(`25-34`:`75+`, sum)) %>%
  pivot_longer(everything(), names_to = 'Age', values_to = 'Number TRUE') %>%
  mutate(`% of Sample` =  100*round(`Number TRUE`/128,2),
         `Text Label` = str_c(`% of Sample`,"%"))%>%
  
  ggplot(aes(x = Age, y = `% of Sample`)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(breaks = seq(0,100,by=10), limits = c(0,50)) +
  geom_text(aes(label=`Text Label`), 
            position=position_dodge(width=0.9), vjust=-0.25) + 
  theme_bw()
  
         


```
