---
title: "Create long and wide datasets"
format: html
editor: visual
author: Joel N Fishbein, M.A.
date: March 24, 2022
---

# Read in data and libraries

```{r}
library(here)
library(tidyverse)

data.allvars <- read_csv(here('TeleACT-Aging_Joel_9-16-22.csv')) %>%
  mutate(ageMeanCentered = age - mean(age),
         ageCenteredAt35 = age-35,
         ageCenteredAt45 = age-45,
         ageCenteredAt55 = age-55,
         ageCenteredAt65 = age-65)

```

# Select variables to examine

```{r}



data.wide <- data.allvars %>%
  select(
    starts_with(
      c("ID", "Telehealth", "age", "Age_Bi",
        "BPIinterference", "BPIseverity",
        "CPAQ.", "CPAQ_Activities", "CPAQ_Willingness", "PHQ9",  "incomelevel", "Income_Coded",
        "MaritalStatus_Coded"))) %>%
  mutate(Income = factor(Income_Coded,
                         levels = c(0:6),
                         labels = c("Under $20K",
                                    "$20-35K",
                                    "$35K-50K",
                                    "$50K-65K",
                                    "$65K-80K",
                                    "$80K-100K",
                                    "100K+")))


```

# Pivot long

```{r}

data.long <- data.wide %>%
  pivot_longer(cols = BPIinterference.1:CPAQ_Willingness.5,
               names_to = c("instrument", "timepoint"), names_pattern = "(.*).(.)")


```

# Write files

```{r}

write_csv(x = data.long, here('Generated Datasets', 'data_long.rds'))
write_csv(x = data.wide, here('Generated Datasets', 'data_wide.rds'))
```
