---
title: "Slope by Age Plot"
format: html
editor: visual
---

```{r}

library(tidyverse)
library(here)

BPIinterference.piecewise.fit <- read_rds(file = 
            here('Model fits',
                 'Unmoderated',
                 'BPIinterference.piecewise.fit'))

BPIseverity.piecewise.fit <- read_rds(file = 
            here('Model fits',
                 'Unmoderated',
                 'BPIseverity.piecewise.fit'))

data.wide <- read_csv(here('Generated Datasets', 'data_wide.rds'))

```

# 

# Extract predicted values

```{r}

BPIinterference.predicted <- 
  bind_cols(age = data.wide$age,
lavaan::predict(BPIinterference.piecewise.fit)) %>%
  mutate(outcome = "Pain Interference (BPI)")

BPIseverity.predicted <- 
  bind_cols(age = data.wide$age,
lavaan::predict(BPIseverity.piecewise.fit))  %>%
  mutate(outcome = "Pain Severity (BPI)")

```

```{r}

combined.predicted <-
  bind_rows(BPIinterference.predicted ,BPIseverity.predicted ) %>%
  select(-myIntercept) %>%
  pivot_longer(slope1:slope2, names_to = "Parameter")

```

# Plot

```{r}

combined.predicted %>%
  ggplot(aes(x = age, y = value)) +
  geom_point() +
  stat_smooth(method = "lm") +
  theme_bw() +
  facet_grid(outcome ~ Parameter)



```

g
